### ISSUE TITLE
Fix editing template definition without a content-type + clear error message

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2SexyContent#103]
When I open a template definition without a content-type it resets the drop-down, so I can't save.

Note also that the system doesn't give an error message if the main entry is selected, but just prevents saving, pls fix

![image](https://cloud.githubusercontent.com/assets/5321186/5088396/675cd678-6f33-11e4-8bea-771bafadac37.png)

**Comment by raphael-m** [comment]
Fixed - I've removed the "No Content Type" option (because <choose ContentType> does the same thing)
