### ISSUE TITLE
Decouple TokenEngine and RazorEngine from ModuleDataSource

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2SexyContent#128]
Currently they are strongly coupled with the ModuleDataSource instead to the ViewDataSource. Because of that Streams can't be exchanged.

**Comment by BeniGemperle** [comment]
Create almost working solution in this branch:
https://github.com/2sic/2SexyContent/tree/Engines-with-ViewDataSource

**Comment by iJungleboy** [comment]
Urgent. Pls do on 2015-02-24
