### ISSUE TITLE
Correct text about pipeline designer

### ISSUE THREAD

**Issue by 2sicProgrammers** [2sic/2SexyContent#134]
Wrong: 
![image](https://cloud.githubusercontent.com/assets/6663382/5779593/5f6cf49e-9da4-11e4-9f60-ebb87a32ce03.png)

New text under the title:
Use the Pipeline-Designer to create queries to data from 2sxc, SQL, RSS and more. 
then the button with label "Visual Pipeline Designer"

**Comment by raphael-m** [comment]
Done
