### ISSUE TITLE
Update view-identifier in url to allow various versions, like details/27

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2SexyContent#145]
First we have to discuss what to allow. Currently it needs 2 words separated by a slash, like
* view/details
* products/details
* seo-word-1/seo-word-2

This causes URLs to get very long if additional params are needed, so it would be good to do something like
details/*

The main question is, what is our syntax. I recommend to only allow "*" = any character for now, but in the future it may actually have more complex logic. So we could
* details/* - easy to understand and duplicate
* details/.* - harder to understand, but would be reg-ex compliant if we ever introduce that...but if we ever introduce reg-ex, then it might be better to require certain things, so maybe we'll then offer a new syntax

So currently details/* is my favorite, while details/.* is kind of better but more confusing and since we don't really support reg-ex, it would only confuse people. 

What do you think?

**Comment by iJungleboy** [comment]
Decided to go with .* - so:
details/.*

**Comment by BeniGemperle** [comment]
Each template is now checked if it matches either:
* a KeyValuePair from the URL like "view/details" (case insentitive string comparsion)
* or a QueryString-Key like "details/123" (case insentitive string comparsion)
