### ISSUE TITLE
Share list records between different instances of the same app

### ISSUE THREAD

**Issue by mconta** [2sic/2SexyContent#152]
Hello,

here is a scenario where I can't figure out how to avoid duplication of data.

I created an app with List support, this app initially has been used in one page of the web site presenting a list of customers (12 user's stories in 5 languages), let's call this records (items) C1,C2..C12

Now the same app is present on 15+ different pages where I need to show a subset of the initial list, imagine for the page A only customer C1,C2,C3 and for the page B only items C4,C5 and C6.

In the new pages I added (not linked) a new 2sic app, configured as the first app and here resides the problem.

Every instance presents an empty list of records, and I need to re-enter the data duplicating content.
This is a problem because every time we duplicate content we duplicate it in 5 languages.

Is there the possibility to choose in the list of records if we want to add a new record or if we want to link an existing one ? 

This could resolve the duplication issue and it will give a more maintainable code.

Do you have any suggestions ? 

Thanks in advance,

Matteo

**Comment by iJungleboy** [comment]
There are two very simple ways to do this :). 
...unless I understood you incorrectly. 

Basically you have follow-up pages, which should show a manual selection of existing items - in the same way as in other places - correct?

**Comment by mconta** [comment]
Yes, this is my scenario .... you understood the problem. 

The follow up pages needs to show a selection of items already defined and optionally need to add new items to the main list for specific information.

**Comment by mconta** [comment]
If the answer is simple I'm really missing something about the 2sxc features and functionality :-(

**Comment by iJungleboy** [comment]
In the edit-dialog, there is a button with "...". This hides advanced functionality like "Replace with exitsnig content" :)

Have fun!

**Comment by mconta** [comment]
Hidden feature...
Thank you , this solves my problem but arises a reflection: don't hide functionality, keep your work visible because after some usage of the UI people like me get used to it, and don't see buttons they don't actually use.

There was also a bug in the past that caused the "..." button to disappear when clicked... so I think that many users don't care about it... 

Thank you again, but keep your great work visible and not hidden under three small bullets :-)

**Comment by mconta** [comment]
Last question, I need to delete the duplicated items, is there a simple way to find in what pages an item has been used ? Thank you for the patience.

**Comment by iJungleboy** [comment]
Hi Mateo
Nope, this feature doesn't exist :(. 

But you could create it :)

**Comment by iJungleboy** [comment]
Solved and closed using existing functionality behind the "..." button.
