### ISSUE TITLE
Admin UI: Surface Data Export/Import Functionality

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2SexyContent#155]
There are some powerful export/import tools but we kept them hidden till now. Let's show them. 

Make sure these functions can be found. 
1. Rename Tab "Content" to "Content / Data"
2. Add buttons below that called "Export Data (beta)" and "Import Data (beta)" as the grey buttons just like the "New Template" button in Views/Templates. Make them open the respective dialog.

![image](https://cloud.githubusercontent.com/assets/5321186/6336842/dcbf4ac2-bba5-11e4-98d8-4d797bbbc9a4.png)

Prevent too much confusion with exiting Import/Export
1. In the Import/Export tab, change title from "Import" to "Import Package with Configuration, Data and Templates"
2. Add note for all who are on the wrong tab for now like this 'To export / import data (like tables of employees, etc.) use the import/export in the "Content / Data" tab.'

![image](https://cloud.githubusercontent.com/assets/5321186/6336893/42191128-bba6-11e4-810a-d82aa64b87a7.png)

**Comment by iJungleboy** [comment]
I can't find the buttons, so I think it was accidentally closed.

**Comment by grayspace** [comment]
Can't see the buttons when you first go to Content/Data tab, but when you click on "Show Items" in the records column and then click "back", they will appear in the Content/Data tab.

Version 6.6.5

**Comment by iJungleboy** [comment]
seems to work now in 7.0 beta. Can close.
