### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by mconta** [2sic/2SexyContent#164]
Hi all,

we found some performance problems in the pages that are using 2sic apps.
The problem we discovered is that, on our server , every istance of the 2sic APPS spends at least 300ms of execution time.

Multiply this time to 5-6 different instances for every page and we get 2 seconds spend on the server only for the 2sic APPS rendering.

I did some test and I found that this behavior is independent from the data and the templates used, also is independent from the technology used (Tokens vs Razor).

Here are some screenshots, the app in the example is a simple token app with no data linked and no additional configuration.

2sic is updated to the latest version.

<b>2sic APPS performance: 3 modules x 300ms = 900+ms </b>
![image](https://cloud.githubusercontent.com/assets/2010201/6410295/718de62a-be6e-11e4-9228-34842315f3b6.png)

<b>2sic APPS Details : </b>
![image](https://cloud.githubusercontent.com/assets/2010201/6410507/3529d32c-be70-11e4-963c-ed8747ebfd01.png)

<b>SIMPLE DNN HTML MODULE performance: </b>
![image](https://cloud.githubusercontent.com/assets/2010201/6410283/4eb33236-be6e-11e4-918a-bde5a594bab7.png)

<b>SIMPLE DNN HTML details:</b>
![image](https://cloud.githubusercontent.com/assets/2010201/6410546/67cc6fc4-be70-11e4-9305-eb68453788b8.png)

Please give me some suggestions on how to increase performance, with the actual behavior 2sic APPS are usable only with few instance on every DNN page.

I clearly understand that 2sic does "a lot of work" under the hood but with simple contents it should be work very fast.

All the best,
Matteo

**Comment by iJungleboy** [comment]
Thanks for the feedback - and many thanks for the detailed analysis, this is very helpful. 

I'm guessing that we have to improve something - but we must corner it first. We'll look into it within the next few days.

**Comment by iJungleboy** [comment]
I'll prioritize this, as I believe that probably many are affected. 
Raphael: can you do a review on this till March 9th so we can try to fix it till March 13th?

**Comment by mconta** [comment]
Thank you, can you keep me updated on this thread if you find any fix/solution? 

In the next days I'm going to replace unimportant apps with the static HTML version ... this will duplicate some content but we are going to gain 1 sec performance improvement on every page.
I prefer to keep the 2sic APP version, but I also need to improve performance asap. 

I'll keep 2sic apps for complex module with data binding, used 2 of theme per page, this could be a good compromise. 

Thanks again for the support.

**Comment by iJungleboy** [comment]
Mateo: could you try our newest release 6.6.4? Just to verify that the problem still exists. 

BTW: I would like to reproduce your debuging environment - could you write a blog about it :)?

**Comment by mconta** [comment]
Hi iJungleboy, 

I tested the new release but I found no performance improvements, after multiple executions the page with 3 APPS takes 962 ms , the page with 3 HTML modules takes 81 ms (pre-rendering time).

Total HTTP execution time is 1870ms  vs 870 ms.

**Comment by mconta** [comment]
If you want to check my specific DNN configuration (and you have the time) I can create a temp admin user, contact me by email for details.

**Comment by mconta** [comment]
Hi, I did some investigations ... it seems that one of the longest operations done by the 2sic apps is the Add creation using the GetApp function : 

![image](https://cloud.githubusercontent.com/assets/2010201/6431294/726fa0ec-c02b-11e4-9551-c2a96ca9640e.png)

![image](https://cloud.githubusercontent.com/assets/2010201/6431305/c976e166-c02b-11e4-8465-eaa335bc62b6.png)

![image](https://cloud.githubusercontent.com/assets/2010201/6431291/4ef3af14-c02b-11e4-8f98-d4914b58ab4c.png)

I tried adding some caching to the App accessor and I got a 50% performance improvement : 

        public static App GetApp(int zoneId, int appId, PortalSettings ownerPS)
        {
            // Get appName from cache
             string appCacheKey = "2sic" + appId.ToString() + zoneId.ToString();
          
            if (HttpContext.Current.Cache.Get(appCacheKey)!=null)
                return (App)HttpContext.Current.Cache.Get(appCacheKey);
....


            HttpContext.Current.Cache.Insert(appCacheKey, sexyApp, null, DateTime.Now.AddMinutes(10), System.Web.Caching.Cache.NoSlidingExpiration);

            return sexyApp;
        }



Clearly it's up to you tell me if this is a valid approach or not and if this approach may lead to inconsistent apps,  but a cache of the app property seems to increase the performance.

**Comment by iJungleboy** [comment]
This is very valuable input, thanks!

**Comment by SCullman** [comment]
I run into similar or same issue with 2sxc Content (https://sexycontent.codeplex.com/discussions/582280). I was curious whether the proposed fix might help also in my case and run a few tests: I can't notice any improvement of the performance in Content mode.

**Comment by iJungleboy** [comment]
We're guessing that somewhere in the system there is something that doesn't access the cache but goes for the DB. This often causes a Ping-Pong of requests. We had such an issue in V4 and the impact was surprisingly big. We're guessing that through certain feature-additions this crept in again somewhere. We'll look at it next week.

**Comment by SCullman** [comment]
I modified SexyControlEditBase and cached the constructor calls of SexyContent in the Sexy and SexyUncached Properties. I don't know whether this is a stupid idea to cache SexyUncached; however these changes shortened the processing time for a page with 7  more or less simplest Content instances from about  350 ms down to 160ms in my setup.

```javascript
protected SexyContent Sexy
{
    get
    {
        if (_sexy == null && ZoneId.HasValue && AppId.HasValue)
            _sexy = RetrieveSexyContent(ZoneId.Value, AppId.Value, true, ModuleConfiguration.OwnerPortalID);
        return _sexy;
    }
}

private SexyContent RetrieveSexyContent(int zoneId, int appId, bool cache, int ownerPortalID)
{
    // Get appName from cache
    string cacheKey = String.Format("2sic:Content:{0}:{1}:{2}:{3}", appId, zoneId, cache, ownerPortalID);
    var cached = DataCache.GetCache<SexyContent> (cacheKey);
    if (cached != null) return cached;
    var sexy = new SexyContent(zoneId, appId, cache, ownerPortalID);
    DataCache.SetCache(cacheKey, sexy);
    return sexy;
}
```

**Comment by mconta** [comment]
Hi Stefan, 

thank you for your snippet, I'll try it as soon as possible. This issue is making me crazy, It's like having a Ferrari and cannot use it because it consumes too gas :-(

**Comment by iJungleboy** [comment]
This might work - but actually the new SexyContent(...) should already work with cached material - so at best this solution "hides" a deeper lying problem, at worst it may not refresh the cache when it would have to. So I would recommend to wait till we look at it next week - or look deeper. My main question is if there are an DB requests during a page load, because (after the initial load) there should be none.

**Comment by mconta** [comment]
We found using sql profiler an abnormal call to the sql stored procedure "dbo.GetModuleSettings", this calls opened also a lot of sql connections. 

I hope this aspect should be managed using a caching mechanism.

Here are the tests done using the 2sic modules, this is the total time to get the page: 

No modules in page : 800 ms
1 app   1.22 sec
2 apps  2.37 sec
4 apps  3.81 sec
5 apps   4.57 sec

**Comment by iJungleboy** [comment]
This doesn't sound like our request - DNN should cache all those requests already. 
BTW: What infrastructure do you have with this performance issue? Azure, VM, Local pc, sql same-system, separate, caching on ...? evoq or Dnn? what version of dnn?
Thanks, Daniel

**Comment by mconta** [comment]
We use DNN Platform 07.03.04 (45) on a server in our company, the Sql server is Sql 2008 standard edition on the same server.
Step to reproduce the problem:

- create a page with simple html content
- measure time taken 
- add progressively N simple apps with token template and without any data connected
- every app add a fixed time to the page (300ms-700ms).
- tested also on Amazon web server , server type C3.large with Window 2012 R2,4Gb Ram 2CPu 2.78Ghz Processor Xeon E5-2680 v2 : same timing as on our web server.
- deleting the apps the page is rendered again under one second
- tracing with sql profiler shows hundreds of call to GetModuleSettings

**Comment by iJungleboy** [comment]
thanks!

**Comment by mconta** [comment]
Here are the SQL trace result , the trace starts after the completition of the first page request, so the module should be cached:

- page with 1 DNN HTML Module : 0 Sql requests, 400ms web execution
- same page with 1 2sic APP  :   697ms , difference is 397ms
on sql :
<br>
Exec dbo.GetHostSettings	2<br>
exec sp_executesql N';Exec dbo.GetModuleSettings 6163	<b>76</b><br>
exec sp_reset_connection 	<b>77</b><br>
Total additional time spent on Sql server : 267ms 
- same page with <b>10 apps</b>  : 3,27 sec time<br>
on SQL:<br>
760 exec sp_reset_connection 	2<br>
760 exec sp_executesql N';Exec dbo.GetModuleSettings 	2.495 sec 	<br>
<br>
Note: this performance measurement are taken from my dev pc with the best performance (I7 processor with SSD disks),  on production environment the times are 4x slower.

**Comment by iJungleboy** [comment]
This very, very odd. Basically 2sxc needs 1 single number from the modulesettings - and this should be cached by DNN. And even if it were not cached, it should never take 300ms to retrieve. Thanks for the analysis.

**Comment by mconta** [comment]
Did you be able to reproduce the problem ?

**Comment by iJungleboy** [comment]
I was going to let Raphael do this next week. But I ran a quick simulation on my system and can confirm, that a single app causes around 200 - 250 requests asking for the GetModuleSettings, each time requesting the same module-id. This is clearly a bug. 
And yes, 10 modules cause 10x so many requests.

**Comment by mconta** [comment]
Thank you, I'm happy that the problem has been reproduced.

Here is a fix that solves the main problem, we added a 1 min cache to the GetModuleSettings SP call, so all the requests from the same method call are managed with the cached version, here is the code taken from the class SexyContent\SexyContent.cs : 

        public int GetContentGroupIdFromModule(int ModuleID)
        {
            var moduleControl = new ModuleController();

            string cacheid = string.Format("2sicmodsett{0}", ModuleID);
            if (HttpContext.Current != null && HttpContext.Current.Cache != null && HttpContext.Current.Cache[cacheid] != null)
                return  Convert.ToInt32(HttpContext.Current.Cache[cacheid].ToString());

            var settings = moduleControl.GetModuleSettings(ModuleID);

            // Set ContentGroupID if not defined in ModuleSettings yet
            if (settings[ContentGroupIDString] == null)
                moduleControl.UpdateModuleSetting(ModuleID, ContentGroupIDString, ModuleID.ToString());

            settings = moduleControl.GetModuleSettings(ModuleID);

            if (HttpContext.Current != null && HttpContext.Current.Cache != null)
                if (HttpContext.Current.Cache[cacheid] == null)
                    HttpContext.Current.Cache.Insert(cacheid, settings[SexyContent.ContentGroupIDString].ToString(), null, DateTime.Now.AddMinutes(1), System.Web.Caching.Cache.NoSlidingExpiration);

            return int.Parse(settings[SexyContent.ContentGroupIDString].ToString());
        }

**Comment by iJungleboy** [comment]
The interesting thing is that the module-setting itself actually can never change :). It's a set once never touch setting (per module).

**Comment by SCullman** [comment]
Well, I don't see a dnn bug here:
getModuleSettings() is a **function** to retrieve the settings from database.
The cached version is simply the property "Settings" from everything which inherits from PortalModuleBase, it is a hashtable which contains the combined module and tab module settings.

If you don't use that property, the developer is responsible for caching.

**Comment by SCullman** [comment]
Matteo, I applied your proposed code change on my dev machine, and I can confirm that this alone solves at least my performance issues. 
Thank you

**Comment by iJungleboy** [comment]
@scullman thanks for that info on the getmodulesetting. In this case that's the main bug - it should not use that,  it should always use the hashtable. And after setting in it has to endlsure dnn does the hash-refresh (though its probably automatic).

**Comment by mconta** [comment]
Hi Stefan,  I'm happy that it works!

**Comment by raphael-m** [comment]
In my dev environment with DNN 7.2.0, `ModuleController.GetModuleSettings()` did not cause any database calls. I can reproduce the issue with DNN 7.4.0, so it looks like DNN changed something between those versions.
I applied the fix above (thank you @mconta) and optimized some other things - please try the new version: https://github.com/2sic/2SexyContent/releases/tag/v06.06.05

**Comment by mconta** [comment]
Really nice Raphael ! Thanks ! I'm going to install it asap.

**Comment by iJungleboy** [comment]
@raphael-m thanks for the checks. Please post an issue on DNN because such a change can easily impact the performance for many things. Thanks for implemting a temporary cache anyhow - let's hope we can remove it again some day.

@mconta & @SCullman pls test and give feedback, many thanks!

**Comment by iJungleboy** [comment]
I tested it on my system, performance is awesome again :) Any feedback from @mconta & @SCullman?

**Comment by mconta** [comment]
Hi all,

I installed the new release on my production environment and it works very fast, on average 1 sec better then before.
I saw in the code a "1 day" cache for the getModuleSettings.... pretty extreme but really effective.

Thanks @raphael-m and @iJungleboy

**Comment by iJungleboy** [comment]
Perfect :). 
Yes, 1 day is no problem. There is nothing in the code and no UI which can ever change the value. The only reason we decided to apply time limit is because we're going to refactor it in a few weeks to use a GUID instead of an Int, and we wanted to be sure that a farm-server would still timeout the data some time :).
