### ISSUE TITLE
Add "Export for Translating" and "Import Translations" features.

### ISSUE THREAD

**Issue by mconta** [2sic/2SexyContent#171]
On multilingual web sites it's a really time consuming process to add the translations on a custom App.

This is more critical if the translation need to be done on List items, the complexity and time raises by a factor directly related to the items number and the number of languages.

Imagine a list with  20 items, every item has a title and a HTML content that need to be translated.
This in 4 languages :  IT,ES,DE and FR, the default is EN

The total is 20 list items x 2 fields x 4 languages = 160 editing actions.

A nicer approach should be preparing a master version in the default language (i.e. EN) and export it <strike>in N different files , one per language.</strike>

Sent the file to the translation agency(ies) and wait for the translation (with a cup of coffee).

When the files arrive (not at the same time since different people translates them) the user should choose a target language and load the items translation.

If in the meantime an item was deleted its translation will be not loaded.

The actual Export format is not really usable by the translators because it has encoded html entities that needs to be converted back in HTML. 

An HTML format should be good , usually translation agencies works with translation programs that extracts only the text component from the HTML. 

The key point of this proposal is to be able to work in parallel with the translation agency decoupling this operation and avoiding the direct HTML editing on every field for every language,

What do you think about ?

**Comment by mconta** [comment]
I also posted a similar proposal on the DNN web site regarding the translation of the pages,  please give it a look :

http://www.dnnsoftware.com/voice/translation-export-import-localized-pages

**Comment by iJungleboy** [comment]
Hi Matteo
I haven't made any videos yet, but actually the data can easily be edited in Excel. So my recommendation is to open it in excel, save it in a format that the externals can use - then re-process as needed when it comes back. Basically you can then always choose if you want 1 language per file, many languages per file etc.

Currently the export/import is just the necessities - so that a pro can work with it and that everything is possible. Right now we wouldn't have any resources to change it from that. But in many cases it would probably just need some documentation, tipps/tricks on how to solve problem X with 2-3 manual steps in Excel. Maybe you could play through some scenarios and create a guide or something :)

**Comment by mconta** [comment]
The export function creates an XML files and this can be opened by Excel.
I see 2 main problems here : 
1) We need to export in another format and next import back to excel and next import the app in DNN. This are 2 extra steps.
2) Editing HTML inside a excel is not really simple, and also directly editing the XML since the HTML is encoded, like this : 
<xmp>

  <Value Key=&quot;ContactAndTryHorizontal&quot; Value=&quot;&amp;lt;div class=&amp;quot;col_12 
column nocolmargin&amp;quot; style=&amp;quot;text-align: center;&amp;quot;&amp;gt;&amp;lt;a 
class=&amp;quot;imaButtonProd aleft&amp;quot; href=&amp;quot;/Support/Download&amp;quot;
style=&amp;quot;&amp;quot;&amp;gt;Try for free&amp;lt;/a&amp;gt; 
&amp;lt;a class=&amp;quot;imaButtonProd&amp;quot; href=&amp;quot;/Contacts&amp;quot;&amp;gt;Contact US&amp;lt;/a&amp;gt;
&amp;lt;/div&amp;gt;&amp;#xD;&amp;#xA;&quot;  Type=&quot;String&quot;&gt;

</xmp>

This is a simple button with the text "Try for free", imagine with complex html texts how can be the translator's work finding the text occurrences.

I think that this is not a a viable option. If you can publish in the future some FAQ or documentation on how to simply do that I will appreciate.

Here is another problem  : I also did some test and the export function works well with simple apps but fails on complex apps with list of items.

Here is the error : 
<pre>
DotNetNuke.Services.Exceptions.PageLoadException: Value cannot be null.
Parameter name: value ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at ToSic.SexyContent.ImportExport.XmlExport.ExportXml(String[] AttributeSetIDs, String[] EntityIDs, String[] TemplateIDs, List`1& Messages) in c:\Sviluppo\Viareggio\ImagicleSite\NewWeb\DNN-Updates\2SexyContent-06.06.04\2SexyContent-06.06.04\SexyContent\ImportExport\XmlExport.cs:line 142
   at ToSic.SexyContent.Export.btnExport_Click(Object sender, EventArgs e) in c:\Sviluppo\Viareggio\ImagicleSite\NewWeb\DNN-Updates\2SexyContent-06.06.04\2SexyContent-06.06.04\Administration\Export.ascx.cs:line 67
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace ---
</pre>

The bug can be obviously fixed in some time, but I think that the steps you are suggesting are a little too "tricky" for a production environment.

So at the moment the best way to translate 2sic apps is to manual translate every language online using the items HTML editor.

**Comment by grayspace** [comment]
I have recently been getting the exact error @mconta  posted above (ToSic.SexyContent.ImportExport.XmlExport.ExportXml). 

I have created a C# razor app with about 16 content items, and now I can't export any of my apps. I was not sure if this was something on my end or a bug with 2sxc, as the error message is not very clear to me. 

Is there a limit on the number of items an app can have? Is there something else I should look into to fix this?

**Comment by iJungleboy** [comment]
App-export seems to have a bug, we're looking into it...

**Comment by iJungleboy** [comment]
Fixed in the newest 6.6.6
