### ISSUE TITLE
Page Picker: Pages with a redirect not visible

### ISSUE THREAD

**Issue by pascalmoser** [2sic/2SexyContent#181]
The page picker does not show pages which have a redirect configured.

**Comment by iJungleboy** [comment]
Why would you want to point to a page which redirects? I mean, it redirects to somewhere else anyhow...

**Comment by raphael-m** [comment]
The problem is that the subpages of those pages are not visible.

**Comment by iJungleboy** [comment]
Ok. But I assume this is a "standard" dnn feature, right?
In that case, we won't try to fix it ourselves - simply out of scope. Though it's not nice, it's easy to work around. 
Because of this I'll close this for now. If you see any need, please post to DNN.

**Comment by raphael-m** [comment]
@iJungleboy, I'm not sure if it's a DNN standard "feature"... maybe we could add a property to the page picker control to make redirecting pages visible.

**Comment by raphael-m** [comment]
Looks like the property is called **IncludeAllTabTypes**: [DNN-3878](https://dnntracker.atlassian.net/browse/DNN-3878)
