### ISSUE TITLE
<> signs at the view of a razor list template with loop?

### ISSUE THREAD

**Issue by dnastone** [2sic/2SexyContent#182]
i created a razor list template and i get at my website this code from the template:

<code>
&lt;div class="sc-viewport"&gt; 
    <>
			&lt;div>&lt;ul class='sc-menu' data-toolbar='{"sortOrder":0,"useModuleList":true,"isPublished":true}'&gt; &lt;/ul>&lt;/div&gt; 
			&lt;div class="row"&gt; 
</code>

when i delete the for each element from the template the <> are gone.

this is the code from my template:
<code>
&lt;@App.Settings.ListType&gt; 
	@foreach(var set in List)
	{
		var Inhalt = set.Content;

			<div>@Inhalt.Toolbar</div>
			<div class="row">
				<div class="col-md-3">
					<img src="@Inhalt.Hauptbild?w=170&mode=crop" />
				</div>
				<div class="col-md-9">
					<h3>@Inhalt.Titel</h3>
					@Html.Raw(Inhalt.Haupttext)
					<br />
			@if (Inhalt.InternerLink != "")
			{
				<a href="@Inhalt.InternerLink" title="@Inhalt.InternerLinkText" role="button">@Inhalt.InternerLinkText</a>
			}
			@if (Inhalt.ExternerLink != "")
			{
				<a href="@Inhalt.ExternerLink" target="_blank" title="@Inhalt.ExternerLinkText" role="button">@Inhalt.ExternerLinkText</a>
			}
				</div>
			</div>			
	}
&lt;/@App.Settings.ListType&gt; 
</code>

**Comment by iJungleboy** [comment]
Just to be real sure you're fixing the right problem...
what does @App.Settings.ListType contain? I'm guessing that's empty, so you get the <>

**Comment by iJungleboy** [comment]
No more feedback, assume it was a user error where @App.Settings.ListType was blank. Close.
