### ISSUE TITLE
Can't Delete Apps From App Management

### ISSUE THREAD

**Issue by grayspace** [2sic/2SexyContent#184]
When I open App Management & click the red "X" buttons in app rows, nothing happens... the delete dialog does not appear. No errors are logged.

**Comment by iJungleboy** [comment]
Thanks. Pls check
1. use the newest 6.6.6
2. Does the browser report a JS error in the console?

Thank

**Comment by grayspace** [comment]
Updated to 6.6.6. Now working as expected... Thanks!

**Comment by iJungleboy** [comment]
close.
