### ISSUE TITLE
PopUp windows closes

### ISSUE THREAD

**Issue by dnastone** [2sic/2SexyContent#190]
i have a portal where i installed 2sexycontent versoin 6.6.6 but there i can't add a new item.
when i click on new the pop up opens and close after a view seconds and the page get's reloaded with that url and i can edit a item, but can't create a new one:
http://www.spenden.at/home/ctl/editcontentgroup/mid/1904/editmode/new/sortorder/2/contentgroupid/1904?returnurl=http://www.spenden.at/home&popup=true

i have no error message at the dnn evens and no javascript error at the google chrome console.
i'm using dnn 7.3.4 with german language.

**Comment by iJungleboy** [comment]
I don't have a real answer yet, but I suggest you check 
* all language settings in DNN & 2sxc
* all portal-urls (especially language-specific)
* things like "does DNN have a right home or search page configured"

Without these, DNN sometimes does strange redirects. 

Did you previously have another version that worked, or is this a new install?

**Comment by dnastone** [comment]
my portal isn't multi language, i only use german.
the home tab are set correctly. the popup window works everywhere at the portal except 2sexycontent.

**Comment by iJungleboy** [comment]
* new install or upgrade?
* issue on both content and apps, or only one?
* admin-dialog would work, or does that close too?

**Comment by dnastone** [comment]
when i click on admin the pop up opens.
then i go to the content types and when i click on new content type the popup close and the page refrseh with that url
http://www.spenden.at/home/ctl/eavmanagement/mid/1909/appid/6/managementmode/contenttypeedit?popup=true

and the text link new content type are hidden.

if you want i can send you per email a system login that you can look at it.

**Comment by dnastone** [comment]
it's an ugrade. the first version i installed was the 6.6.5 but there i had the same problems

**Comment by iJungleboy** [comment]
you're the only person we know of who reported this problem. to 99% it's a dnn-issue. Typically because there is no search-page or similar configured in your language... - such things mess up the URL-rewriter and cause such issues. 

If you checked those aspects and it still doesn't work, pls send us a host login to info@2sxc.org

**Comment by dnastone** [comment]
it's interesting, the error only happend on the tab which is the start tab at the portal
when i change the start tab to an other tab, the popup window works.

**Comment by iJungleboy** [comment]
Yes, sounds like a url / standard-something-page issue. DNN based. 
If you check all your DNN-portal-settings etc. you should probably be able to fix it.

**Comment by iJungleboy** [comment]
@dnastone from what you wrote I'll assume it's a DNN/URL-Issue. I'll close this for now, if I'm wrong, pls re-open this.
