### ISSUE TITLE
Export file should contain ="" or =() instead of =default() everywhere...

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2SexyContent#202]
because =default() is confusing in many cases. 

Alternative IF we can't get it to go through excel-nicely:
* =("") >> means it's just an empty string 
* =() >> means it's null

**Comment by tobias2sic** [comment]
We use =("") for empty strings and =() for nothing. Take care, old exports with =default() do not work anymore.

**Comment by tobias2sic** [comment]
The special tag know are:
[]    >> Null
[""] >> Empty
[ref(en-US,ro)] >> Reference to language
