### ISSUE TITLE
Pressing "Cancel" in export & import dialog should go back

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2SexyContent#205]
...it currently closes the lightbox and goes to another page, not good. 
![image](https://cloud.githubusercontent.com/assets/5321186/7370856/3241433a-edbd-11e4-807c-86792269449a.png)

also happens in import
![image](https://cloud.githubusercontent.com/assets/5321186/7370900/8b5b9dc6-edbd-11e4-88a9-b060bd3f677b.png)

**Comment by tobias2sic** [comment]
Goes back to EAV management know.
