### ISSUE TITLE
Button "..." in Edit Item Form Disappears when clicked

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2SexyContent#69]
The button just disappears but nothing else is shown. That's confusing. Tested in Chrome 38.

![edit item](https://cloud.githubusercontent.com/assets/6669093/4589302/91a1d79a-5051-11e4-8801-6e73bedb1f15.png)

**Comment by iJungleboy** [comment]
Others have given the same feedback, so they "learned" to ignore the button even though it has important functions.

**Comment by iJungleboy** [comment]
@raphael-m fixed it.
