### ISSUE TITLE
HTML Token Template breaks On-Page AngularJS Modules with empty Brackets []

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2SexyContent#76]
A simple Token Template might contain inline Scripts like this:
```HTML
<script>
angular.module('MyModule', []) ...
</script>
```

But the Result in the Browser is broken:
```HTML
<script>
angular.module('MyModule', ) ... // [] are missing
</script>
```

An easy workaround is to have all JavaScript in an external file.

**Comment by raphael-m** [comment]
We are using the DNN default token provider to resolve the tokens - we can't change the behaviour of it (unless we create our own token provider?).

**Comment by iJungleboy** [comment]
Pls suggest a work-around (maybe "[   ]" works or something similar...)
and maybe also post this as a DNN-bug. Then close.

**Comment by raphael-m** [comment]
I can confirm that the 'empty array initializer' works when adding a whitespace character: "[ ]". I created an issue in the DNN issue tracker: https://dnntracker.atlassian.net/browse/DNN-6598.
